### PR TITLE
HaydenCenter47725474

### PR DESCRIPTION
**Pull request by HaydenCenter**
Can you take a quick look at this code to see if you would consider it "well coded" / easy to understand? It is fully functional, and I am just making sure it is structurally and stylistically sound.

### CODE REVIEW

**Comment by pragdave** [comment]
I like this a lot. I have one minor suggestion and one bigger one.

The minor suggestion: rather than have print() be a special case in the execution, how does it work to have it as a separate nonterminal in the grammar, so

~~~ python
def print_call():                 return ["print","(",call_arguments,")"]
def function_call():            return [variable_reference,"(",call_arguments,")"]
~~~

The bigger observation: in your interpreter, you are't calling the AST to access child nodes: you're doing directly, because the interpreter shares the knowledge of the parse. I think it would be better from a coupling point of view to have the interpreter use `accept` on the values it needs and to have the visitor call it back, rather than just call itself directly.

Very nice job.

Would you consider being a kind of informal TA for the arpeggio group on the 4th?

**Comment by HaydenCenter** [comment]
> I like this a lot. I have one minor suggestion and one bigger one.
> 
> The minor suggestion: rather than have print() be a special case in the execution, how does it work to have it as a separate nonterminal in the grammar, so
> 
> ```python
> def print_call():                 return ["print","(",call_arguments,")"]
> def function_call():            return [variable_reference,"(",call_arguments,")"]
> ```
> 
> The bigger observation: in your interpreter, you are't calling the AST to access child nodes: you're doing directly, because the interpreter shares the knowledge of the parse. I think it would be better from a coupling point of view to have the interpreter use `accept` on the values it needs and to have the visitor call it back, rather than just call itself directly.
> 
> Very nice job.
> 
> Would you consider being a kind of informal TA for the arpeggio group on the 4th?

Hi Professor,

I plan on implementing the separate print call this week. I hadn't really considered straying from the EBNF you provided but I agree that would probably work better. On the topic of the "accept", I'm really not sure what you mean by this, and would love to ask some questions on Wednesday and give it a shot. On the topic of helping with Arrpegio on Wednesday, I would be glad to help after I ask you a few questions as mentioned previously. Thanks for your help

**Comment by pragdave** [comment]
It's a deal

**Comment by HaydenCenter** [comment]
I am still trying to work on changing the code to be more decoupled, but if I cannot get that working on time, this will be the final submission. Otherwise, you will see a new commit come in before tomorrow night.

**Comment by pragdave** [comment]
~~~
00_expr.smu
20_fn_basic.smu
22_closures.smu
01_variables.smu
10_if.smu
21_recursive_fns.smu
02_let.smu
99_fib.smu
~~~
| Passed | Failed |  Grade contribution |
|-:|-:|:-|
56 | 0 | 80.00% (out of 80%)


Do you remember the conversation we had about splitting out the AST from the Interpreter (so that the Interpreter was a visitor on the AST)? I don't see that change in here, and I'm deducting 4 for that. Otherwise, it's a really nice job. I like the way the formatted the code in the grammar: it's a great case of compact-beats-whitespace.

**Pull request closed without merging**
