### PR TITLE
Connor Peters PR

### PR DESCRIPTION
**Pull request by CPetersSMU**
Final Submission

### CODE REVIEW

**Comment by pragdave** [comment]
I am trying to grade this, but I'm not having much luck. 

It doesn't run the tests because your main function expects the actual program as a parameter, but the spec calls for it to accept a file name containing a Smurf script.

I fixed that, and also added the "Print: " prefix on print statements, but it only seems to run the first expression in a file:

~~~
~/t/cs3342_smurf|pr-15 ⚡☡
17∙28∙30≻ src/smurf test_cases/00_expr.smu 
parsing failed
+ program
  + code
    + statement/2
      + expr/3
     . . .
Print: 1
~~~

As it stands I can't give this much of a grade (certainly not one commensurate with the work you put in). I don't like that.

Am I doing something wrong? How am I supposed to test this?

Please let me know TODAY if I'm missing something.



Here's a diff with my changes
~~~
diff --git a/src/Interpreter.cpp b/src/Interpreter.cpp
index 796f3b3..6e0f100 100644
--- a/src/Interpreter.cpp
+++ b/src/Interpreter.cpp
@@ -63,7 +63,7 @@ int Interpreter::evaluatePrint(astNode* node, vector<astNode*> args) {
                out += "|";
        }
        out.pop_back();
-       cout << out << endl;
+       cout << "Print: " << out << endl;
        return 0;
 }
 int Interpreter::evaluateArgs(astNode* node, vector<astNode*> args) {
diff --git a/src/main.cpp b/src/main.cpp
index 3f9c932..63eed03 100644
--- a/src/main.cpp
+++ b/src/main.cpp
@@ -1,6 +1,8 @@
 #include <peglib.h>
 #include <assert.h>
 #include <iostream>
+#include <fstream>      // std::ifstream
+
 #include "astNode.h"
 #include "customAST.h"
 #include "Binding.h"
@@ -39,7 +41,23 @@ int main(int argc, char* argv[]) {
        parser parser(grammar);                                         
                                                        //makes the parser
        parser.enable_ast();
        shared_ptr<Ast> ast;
-       if (parser.parse(argv[1], ast)) {                               
                                        //prints ast
+
+       ifstream input(argv[1]);
+       if (!input) {
+               cerr << "cannot open " << argv[1] << endl;
+               exit(1);
+       }
+
+           // get length of file:
+    input.seekg (0, input.end);
+    int length = input.tellg();
+    input.seekg (0, input.beg);
+
+    char * buffer = new char [length+1];
+    input.read (buffer,length);
+               buffer[length] = 0;
+
+       if (parser.parse(buffer, ast)) {                                
                                        //prints ast
                cout << peg::ast_to_s(ast) << endl;
        }
        else {
~~~

**Comment by CPetersSMU** [comment]
Professor,

If the command line argument is in quotes, my code should see the argument
as a string literall and not go looking for a file name.
A way you could test this code is by running $ Smurf.exe "print(1)", or any
other program, in quotes. This is how I tested and ran my code for the
majority the time I worked on in.

Getting the code correct was my first priority, above having it run with
scripts.
Over the time I wrote the code, I ran each individual test with success,
including the final fibonacci test.

As for why you are only seeing the first line run; I believe I forgot to
include comments with the whitespacing. Which would explain why the first
test statement works, but then breaks once it gets to that #. I apologize
for this oversight.

I hope that answers the questions. If you have any more, please feel free
to ask.

Thank you

-Connor Peters

**Comment by pragdave** [comment]
I'm now about an hour into your code. I've made the changes I described to let it run from files, I fixed the `print` function, and I added support for comments.

That allowed me to run my tests. I get the following result:

## Test results
~~~
00_expr.smu
20_fn_basic.smu
        Test  1         No output
        Test  2         No output
        Test  3         No output
        Test  4         No output
        Test  5         No output
22_closures.smu
        Test  1         No output
        Test  2         No output
        Test  3         No output
        Test  4         No output
        Test  5         No output
        Test  6         No output
01_variables.smu
10_if.smu
21_recursive_fns.smu
        Test  1         No output
        Test  2         No output
        Test  3         No output
        Test  4         No output
02_let.smu
99_fib.smu
        Test  1         No output
~~~
| Passed | Failed |  Grade contribution |
|-:|-:|:-|
40 | 16 | 57.14% (out of 80%)

I then tried running the fib example manually:

~~~
14∙32∙14≻ src/parser test_cases/99_fib.smu 
fish: 'src/parser test_cases/99_fib.smu' terminated by signal SIGSEGV (Address boundary error)
~~~

The same happens with 20_fn_basic

So, grading the functionality based on tests, you'd get about 57% percent contribution to the project grade. If instead I grade based on the functionality matrix, I'd say you were correctly interpreting variables, so that would contribute 64% (80% or 80%), so I went with that.

For the additional 20%, I'm deducting 12% because of the fact I couldn't run the code without modifying it, and asked me to evaluate it both based on tests and the functionality matrix.

**Comment by CPetersSMU** [comment]
Professor Thomas,

I don't know what to say. I had all the tests working for sure. I'm
mortified honestly.
I don't think this is representative of the work I put into this project.
I'm really concerned for my financial future too with the class outcome as
it stands.
Is there anything more I can do to show you I learned what you taught? Like
I said I prioritized my time on getting the code right over running with
scripts. I think in trying to get it to run with scripts I somehow messed
up the actual code. It worked before I submitted it.

-Connor Peters

**Comment by pragdave** [comment]
Following our call, I applied the fix you requested. Life is a lot happier here:

## Test results
~~~
00_expr.smu
20_fn_basic.smu
22_closures.smu
        Test  2         expected: 101   actual:   100
01_variables.smu
10_if.smu
21_recursive_fns.smu
02_let.smu
99_fib.smu
~~~
| Passed | Failed |  Grade contribution |
|-:|-:|:-|
55 | 1 | 78.57% (out of 80%)

This moved you up into B/B+ territory.

**Comment by CPetersSMU** [comment]
I'm so glad.
Thank you so much for everything.

**Pull request closed without merging**
